resources:
  - name: scripts
    type: gitRepo
    integration: scm_gh
    pointer:
      sourceName: ric03uec/seatrial
      branch: master

  - name: reg_dh
    type: integration
    integration: reg_dh

  - name: cloud_aws
    type: integration
    integration: cloud_aws

jobs:
  - name: trigger_u16_base
    type: runSh
    steps:
      - IN: scripts
      - TASK:
          name: verify_image_tag
          script:
            - sudo docker images

  - name: trigger_u14_base
    type: runSh
    steps:
      - IN: scripts
      - TASK:
          name: verify_image_tag
          script:
            - sudo docker images
