resources:
  - name: image_u16_base
    type: image
    integration: reg_dh
    pointer:
      sourceName: drydock/u16
    seed:
      versionName: master
    flags:
      - x86_U16

  - name: image_u16_all
    type: image
    integration: reg_dh
    pointer:
      sourceName: drydock/u16all
    seed:
      versionName: master
    flags:
      - x86_U16

jobs:

  ###################################
  # x86_64 Ubuntu 16 Base Image
  ###################################
  - name: test_u16_base_java
    type: runSh
    flags:
      - x86_U16
    steps:
      - IN: scripts
      - IN: image_u16_base
      - IN: trigger_u16_base
      - TASK:
          name: verify_java_version
          runtime:
            options:
              imageName: drydock/u16
              imageTag: master
          script:
            - java -version

  - name: test_u16_base_ruby
    type: runSh
    flags:
      - x86_U16
    steps:
      - IN: scripts
      - IN: image_u16_base
      - IN: trigger_u16_base
      - TASK:
          name: verify_ruby_version
          runtime:
            options:
              imageName: drydock/u16
              imageTag: master
          script:
            - echo '[[ -s /etc/profile.d/rvm.sh ]] && source /etc/profile.d/rvm.sh' >> /etc/drydock/.env
            - source /etc/profile.d/rvm.sh
            - ruby --version

  - name: test_u16_base_node
    type: runSh
    flags:
      - x86_U16
    steps:
      - IN: scripts
      - IN: image_u16_base
      - IN: trigger_u16_base
      - TASK:
          name: verify_node_version
          runtime:
            options:
              imageName: drydock/u16
              imageTag: master
          script:
            - node --version

  - name: test_u16_base_packages
    type: runSh
    flags:
      - x86_U16
    steps:
      - IN: scripts
      - IN: image_u16_base
      - IN: trigger_u16_base
      - TASK:
          name: verify_packages
          runtime:
            options:
              imageName: drydock/u16
              imageTag: master
          script:
            - git --version
            - rsync --version

  - name: reconcile_u16_base
    type: runSh
    flags:
      - x86_U16
    steps:
      - IN: test_u16_base_java
      - IN: test_u16_base_node
      - IN: test_u16_base_ruby
      - IN: test_u16_base_packages
      - TASK:
          name: compile_results
          runtime:
            options:
              imageName: drydock/u16
              imageTag: master
          script:
            - node --version
            - java -version

  ###################################
  # x86_64 Ubuntu 16 All Image
  ###################################
  - name: trigger_u16_all
    type: runSh
    flags:
      - x86_U16
    steps:
      - IN: scripts
      - IN: reconcile_u16_base
      - TASK:
          name: verify_image_tag
          script:
            - sudo docker images

  - name: test_u16_all
    type: runSh
    flags:
      - x86_U16
    steps:
      - IN: trigger_u16_all
      - TASK:
          name: test_services
          runtime:
            options:
              imageName: drydock/u16
              imageTag: master
          script:
            - cd /u16/test
            - ls -atlh
            - ./_mysql.sh
